### ISSUE TITLE
Suggestion: Add tiredness debuffs for 1.12 (and a compatibility question)

### ISSUE THREAD

**Issue by katubug** [Fuzss/let-me-sleep#2]
Hi! I was looking for a mod that would cause occasional insomnia for a modpack I'm working on. This mod seems to basically fit the bill (I can just have it be weather-based, for example), but I was also hoping for a feature that would cause tiredness (perhaps via potion effects, the way BetterSleeping does?), to force players to sleep every so often. However, if this isn't something you'd be interested in adding, that's completely fine. :) I just thought I'd ask!

My other question is, can I use this mod with something like [SleepingOverhaul](https://www.curseforge.com/minecraft/mc-mods/sleepingoverhaul) or [SimulatedNights](https://www.curseforge.com/minecraft/mc-mods/simulated-nights)? I really like the idea of sleep being a time lapse, but I'd also like the features from your mod. I will try them together when I have the chance, but I figured I'd ask in case an incompatibility was not immediately evident from a layman's perspective. Thank you for your time!

**Comment by Fuzss** [comment]
Hey, thanks for your suggestion. The way I imagine Let Me Sleep is to be a mod for tweaking the existing system instead of replacing it or adding completely new aspects. Adding features like tiredness would therefor sadly be out of scope. 

For the two mods you mentioned I'm pretty sure they're fundamentally incompatible, but you're of course more than welcome to see if maybe some parts work. I'm sorry that my answer has to be quit the let-down.

**Comment by katubug** [comment]
No problem, thank you very much for your response! I appreciate it. :)
